/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hari' at '9/9/17 9:40 AM' with Gradle 2.10
 *
 * @author hari, @date 9/9/17 9:40 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
